schemes:
  cubic:
    name: TCP Cubic
    color: black
    marker: '*'
  vegas:
    name: TCP Vegas
    color: silver
    marker: 'h'
  bbr:
    name: TCP BBR
    color: gold
    marker: '^'
  quic:
    name: QUIC Cubic
    color: magenta
    marker: '8'
  scream:
    name: SCReAM
    color: pink
    marker: '1'
  webrtc:
    name: WebRTC media
    color: brown
    marker: 'v'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
  fillp:
    name: FillP
    color: violet
    marker: '+'
  fillp_sheep:
    name: FillP-Sheep
    color: violet
    marker: 'D'
